mlflow_params:
  model_name: 'wine_rf' # Environment suffix will be added by code # TODO: You need to check this I don't think it's working as intended
model_comparison_params:
  metric: 'roc_auc_score'
  higher_is_better: True